# Generated by Django 2.2.6 on 2019-10-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (optional)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(default='30', verbose_name='Dauer (in Minuten)'),
        ),
    ]
